FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

# Copy package files
COPY pnpm-lock.yaml package.json ./

# Install all dependencies (including dev)
RUN pnpm install --frozen-lockfile

COPY __tests__ ./__tests__
COPY configs ./configs
COPY tsconfig.json .
COPY jest.config.js .
COPY setupTests.ts .

CMD ["pnpm", "test"]